baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Sangraham'
enableRobotsTXT = true
[sitemap]
changeFreq = 'daily'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
